### ISSUE TITLE
Change 'share' to 'exports' ?

### ISSUE THREAD

**Issue by deanrad** [foxbenjaminfox/meteor-coffeescript#1]
First, I applaud the effort to move this out of core, and enhance at the same time. Also - great name for the package.

The globals/share/export thing has been a confusing thing for me lately. 

I know you're trying to avoid the confusion - but would an exports mechanism (see [mrt:exports](https://atmospherejs.com/mrt/exports)) that is already familiar be sufficient, or does `share` do different things underneath to merit keeping separate ?

Thanks again.

**Comment by foxbenjaminfox** [comment]
Thanks for the support. I'll try to clarify the whole globals/share/export thing.

(By the way, I haven't made any changes to this part. This is all as it stands in the core `coffeescript` package.)

All variables that you define are local to the file they are defined in, by default. This is because each file is wrapped in an IIFE.

If you want a variable to be global, you can assign it on the `window` object. Something like: `window.variableName = "value"`. Because the IIFE is invoked with the `window` as its context, you can also do `this.variableName = "value"` (assuming you're in the file's top-level scope, and not in some function which was invoked with a different context), or better yet, `@variableName = "value"` which is identical.

This is kind of bad, as it pollutes the global namespace. So, if you want to define a variable that is accessed in multiple different files, you can define it on the `share` object instead. `share` is basicly just a mini namespace you can use, should you wish to.

None of this involves exporting a variable, and none of them should be used to do so. The trick where you assign to the `window` object could be used for that, as it _does_ polute the global namespace, but that's kind of ugly.

But Meteor does its exporting of variables from packages in a more formal way, using a definition in your package.js. If you define a variable as an export in your package.js, Meteor will do black magic and arrange for it to be available, despite the fact that it would normally be defined locally to a file. In such a case, yes the variable is accessible from all files in your package, but that's not really the point. You shouldn't use it just for that, but rather use the `share` object if you just want to communicate between different files in the same package.

All this about exports only applies to packages, of course. If you're not writing a package, their isn't such things as exports at all, and if you want to communicate between your files you must either use `share` or pollute the global namespace (which is more excusable in this case.)

This is how it now stands - I'm not exactly sure what you're proposing when you suggest an exports mechanism, and how it relates to the current package export mechanism. I do hope that my explanation helps clarify what exactly `share` is. Given this framework, where does what you are suggesting stand?

**Comment by deanrad** [comment]
I see - that definitely clears up some confusion. The name `share` is perfect for this case, and consistent with the Meteor docs (http://docs.meteor.com/#/full/coffeescript) Thanks for the writeup!
